global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api_mykreno"
    static_configs:
      - targets: ["api_mykreno:3000"] # Replace YOUR_PORT with the actual port your app runs on, likely the same as your app's port
  - job_name: "prometheus" # Prometheus scraping itself
    static_configs:
      - targets: ["prometheus:3102"]
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter_mykreno:9187"]
