global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api_mykreno"
    static_configs:
      - targets: ["api_mykreno:3000"]
  - job_name: "prometheus" # Prometheus scraping itself
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter_mykreno:9187"]
  - job_name: "python-ai-service"
    static_configs:
      - targets: ["python-backend:8000"]
  - job_name: "blackbox_http_check"
    metrics_path: /probe
    params:
      module: [http_2xx] # Use the 'http_2xx' module defined in blackbox.yml
    static_configs:
      - targets:
          - "step-test-env-g3d0fpf4afeabpaq.westeurope-01.azurewebsites.net"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
